spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://muze-rdb.ckudumad3jrn.ap-northeast-2.rds.amazonaws.com:3306/muze?useUnicode=yes&characterEncoding=utf-8&autoReconnect=true
    username: admin
    password: muze123123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  tomcat:
    uri-encoding: UTF-8

#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    driver-class-name: org.h2.Driver
#    username: sa
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties.hibernate.hbm2ddl.auto: update
#    showSql: true

api:
  key: 08dcd1b5b0105efc838fc917d5478ed4
  url:
    apiBaseUrl: http://www.kobis.or.kr/kobisopenapi/webservice/rest/
    dailyBoxOfficeUrl: boxoffice/searchDailyBoxOfficeList.json
    weeklyBoxOfficeUrl: boxoffice/searchWeeklyBoxOfficeList.json
    movieListUrl: movie/searchMovieList.json
    movieDetailUrl: movie/searchMovieInfo.json
    actorListUrl: people/searchPeopleList.json
    actorDetailUrl: people/searchPeopleInfo.json
